class SlaveToMaster:
    slave_to_master = [
        {"name": "S2M_AS_SW1", "offset": 0, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_SW2", "offset": 2, "length": 2, "type": "UINT"},
        {"name": "S2M_AV_U", "offset": 4, "length": 4, "type": "Real"},
        {"name": "S2M_AV_I", "offset": 8, "length": 4, "type": "Real"},
        {"name": "S2M_AV_P", "offset": 12, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_Umin", "offset": 16, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_Umax", "offset": 20, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_LIMIT_Umin", "offset": 24, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_LIMIT_Umax", "offset": 28, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_LIMIT_Imin", "offset": 32, "length": 4, "type": "Real"},
        {"name": "S2M_SPV_LIMIT_Imax", "offset": 36, "length": 4, "type": "Real"},
        {"name": "S2M_AS_BATT_R1", "offset": 40, "length": 4, "type": "Real"},
        {"name": "VS2M_AS_BATT_R2", "offset": 44, "length": 4, "type": "Real"},
        {"name": "S2M_AS_BATT_R3", "offset": 48, "length": 4, "type": "Real"},
        {"name": "S2M_AS_BATT_R4", "offset": 52, "length": 4, "type": "Real"},
        {"name": "S2M_AS_BATT_C1", "offset": 56, "length": 4, "type": "Real"},
        {"name": "S2M_AV_BATT_I_filter", "offset": 60, "length": 4, "type": "Real"},
        {"name": "S2M_AV_BATT_U0_A", "offset": 64, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_KP_I", "offset": 68, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_TN_I", "offset": 72, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_KP_U", "offset": 76, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_TN_U", "offset": 80, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_KP_M", "offset": 84, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_TN_M", "offset": 88, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_U_ramp", "offset": 92, "length": 4, "type": "Real"},
        {"name": "S2M_AV_REG_I_ramp", "offset": 96, "length": 4, "type": "Real"},
        {"name": "S2M_AS_REG_ParSet", "offset": 100, "length": 2, "type": "SINT"},
        {"name": "S2M_AS_REG_ParSet_Err", "offset": 102, "length": 2, "type": "UINT"},
        {"name": "S2M_AV_REG_Mode", "offset": 104, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_BATT_Model", "offset": 106, "length": 2, "type": "SINT"},
        {"name": "S2M_AS_ZR_Error_a", "offset": 108, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_ZR_Error_b", "offset": 110, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_UWR_Error_a", "offset": 112, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_UWR_error_b", "offset": 114, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_RK_Error_a", "offset": 116, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_RK_Error_b", "offset": 118, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_TSB_Error_a", "offset": 120, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_TSB_Error_b", "offset": 122, "length": 2, "type": "UINT"},
        {"name": "S2M_AS_BATT_C2", "offset": 124, "length": 4, "type": "Real"},
        {"name": "S2M_AS_BATT_L1", "offset": 128, "length": 4, "type": "Real"},
        {"name": "S2M_AV_BATT_U0_B", "offset": 132, "length": 4, "type": "Real"},
        {"name": "S2M_AS_TSB_Error_c", "offset": 136, "length": 2, "type": "UINT"},
        {"name": "S2M_AV_BATT_SOC", "offset": 138, "length": 4, "type": "Real"},
    ]

    values = {
        "S2M_AS_SW1": 0,
        "S2M_AS_SW2": 0,
        "S2M_AV_U": 0,
        "S2M_AV_I": 0,
        "S2M_AV_P": 0,
        "S2M_SPV_Umin": 0,
        "S2M_SPV_Umax": 0,
        "S2M_SPV_LIMIT_Umin": 0,
        "S2M_SPV_LIMIT_Umax": 0,
        "S2M_SPV_LIMIT_Imin": 0,
        "S2M_SPV_LIMIT_Imax": 0,
        "S2M_AS_BATT_R1": 0,
        "VS2M_AS_BATT_R2": 0,
        "S2M_AS_BATT_R2": 0,
        "S2M_AS_BATT_R3": 0,
        "S2M_AS_BATT_R4": 0,
        "S2M_AS_BATT_C1": 0,
        "S2M_AV_BATT_I_filter": 0,
        "S2M_AV_BATT_U0_A": 0,
        "S2M_AV_REG_KP_I": 0,
        "S2M_AV_REG_TN_I": 0,
        "S2M_AV_REG_KP_U": 0,
        "S2M_AV_REG_TN_U": 0,
        "S2M_AV_REG_KP_M": 0,
        "S2M_AV_REG_TN_M": 0,
        "S2M_AV_REG_U_ramp": 0,
        "S2M_AV_REG_I_ramp": 0,
        "S2M_AS_REG_ParSet": 0,
        "S2M_AS_REG_ParSet_Err": 0,
        "S2M_AV_REG_Mode": 0,
        "S2M_AS_BATT_Model": 0,
        "S2M_AS_ZR_Error_a": 0,
        "S2M_AS_ZR_Error_b": 0,
        "S2M_AS_UWR_Error_a": 0,
        "S2M_AS_UWR_error_b": 0,
        "S2M_AS_RK_Error_a": 0,
        "S2M_AS_RK_Error_b": 0,
        "S2M_AS_TSB_Error_a": 0,
        "S2M_AS_TSB_Error_b": 0,
        "S2M_AS_BATT_C2": 0,
        "S2M_AS_BATT_L1": 0,
        "S2M_AV_BATT_U0_B": 0,
        "S2M_AS_TSB_Error_c": 0,
        "S2M_AV_BATT_SOC": 0,
    }

    def __init__(self):
        pass
