


class MasterToSlave:

    master_to_slave = [
        { "name": "M2S_RS_CW1", "offset": 0, "length": 2, "type": "UINT" },
        { "name": "M2S_SP_U",   "offset": 2, "length": 4, "type": "Real" },
        {"offset": 6,  "name": "M2S_SP_Imin",        "length": 4, "type": "Real" },
        {"offset": 10, "name": "M2S_SP_Imax",        "length": 4, "type": "Real" },
        {"offset": 14, "name": "M2S_SP_Umin",        "length": 4, "type": "Real" },
        {"offset": 18, "name": "M2S_SP_Umax",        "length": 4, "type": "Real" },
        {"offset": 22, "name": "M2S_SP_LIMIT_Umin",  "length": 4, "type": "Real" },
        {"offset": 26, "name": "M2S_SP_LIMIT_Umax",  "length": 4, "type": "Real" },
        {"offset": 30, "name": "M2S_SP_LIMIT_Imin",  "length": 4, "type": "Real" },
        {"offset": 34, "name": "M2S_SP_LIMIT_Imax",  "length": 4, "type": "Real" },
        {"offset": 38, "name": "M2S_SP_BATT_R1",     "length": 4, "type": "Real" },
        {"offset": 42, "name": "M2S_SP_BATT_R2",     "length": 4, "type": "Real" },
        {"offset": 46, "name": "M2S_SP_BATT_R3",     "length": 4, "type": "Real" },
        {"offset": 50, "name": "M2S_SP_BATT_R4",     "length": 4, "type": "Real" },
        {"offset": 54, "name": "M2S_SP_BATT_C1",     "length": 4, "type": "Real" },
        {"offset": 58, "name": "M2S_SP_REG_I_Filter","length": 4, "type": "Real" },
        {"offset": 62, "name": "M2S_SP_REG_U0_A",    "length": 4, "type": "Real" },
        {"offset": 66, "name": "M2S_SP_REG_KP_I",    "length": 4, "type": "Real"},
        {"offset": 70, "name": "M2S_SP_REG_TN_I",    "length": 4, "type": "Real" },
        {"offset": 74, "name": "M2S_SP_REG_KP_U",    "length": 4, "type": "Real" },
        {"offset": 78, "name": "M2S_SP_REG_TN_U",    "length": 4, "type": "Real" },
        {"offset": 82, "name": "M2S_SP_REG_KP_M",   "length": 4, "type": "Real"},
        {"offset": 86, "name": "M2S_SP_REG_TN_M",   "length": 4, "type": "Real"},
        {"offset": 90, "name": "M2S_SP_REG_U_Ramp", "length": 4, "type": "Real"},
        {"offset": 94, "name": "M2S_SP_REG_I_Ramp", "length": 4, "type": "Real"},
        {"offset": 98, "name": "M2S_SP_REG_ParSet", "length": 2, "type": "UINT"},
        {"offset": 100,"name": "M2S_SP_REG_Mode",   "length": 2, "type": "UINT"},
        {"offset": 102,"name": "M2S_SP_BATT_Model", "length": 2, "type": "UINT"},
        {"offset": 104,"name": "M2S_RS_CW2",        "length": 2, "type": "UINT"},
        {"offset": 106,"name": "M2S_SP_P",          "length": 4, "type": "UINT"},
        {"offset": 110,"name": "M2S_SP_BATT_C2",    "length": 4, "type": "UINT"},
        {"offset": 114,"name": "M2S_SP_BATT_L1",    "length": 4, "type": "UINT"},
        {"offset": 118,"name": "M2S_SP_BATT_U0_B",  "length": 4, "type": "UINT"},
        {"offset": 122,"name": "M2S_SP_RPL_LF_Mode","length": 2, "type": "UINT"},
        {"offset": 124,"name": "M2S_SP_RPL_MF_Mode","length": 2, "type": "UINT"},
        {"offset": 126,"name": "M2S_SP_RPL_LF_Hz",  "length": 4, "type": "UINT"},
        {"offset": 130,"name": "M2S_SP_RPL_LF_U",   "length": 4, "type": "UINT"},
        {"offset": 134,"name": "M2S_SP_RPL_MF_Hz",  "length": 2, "type": "UINT"},
        {"offset": 136,"name": "M2S_SP_RPL_MF_I",   "length": 4, "type": "UINT"},
        {"offset": 140,"name": "M2S_SP_RPL_MF_U",   "length": 4, "type": "UINT"},
        {"offset": 144,"name": "M2S_SP_SOC_C_Nom",  "length": 4, "type": "UINT"},
        {"offset": 148,"name": "M2S_SP_SOC_0",      "length": 4, "type": "UINT"},
        {"offset": 152,"name": "M2S_RS_SOC_0",      "length": 2, "type": "UINT"}
        ]

    values = {
            "M2S_RS_CW1":0,
            "M2S_SP_U":0,
            "M2S_SP_Imin":0,
            "M2S_SP_Imax":0,
            "M2S_SP_Umin":0,
            "M2S_SP_Umax":0,
            "M2S_SP_LIMIT_Umin":0,
            "M2S_SP_LIMIT_Umax":0,
            "M2S_SP_LIMIT_Imin":0,
            "M2S_SP_LIMIT_Imax":0,
            "M2S_SP_BATT_R1":0,
            "M2S_SP_BATT_R2":0,
            "M2S_SP_BATT_R3":0,
            "M2S_SP_BATT_R4":0,
            "M2S_SP_BATT_C1":0,
            "M2S_SP_REG_I_Filter":0,
            "M2S_SP_REG_U0_A":0,
            "M2S_SP_REG_KP_I":0,
            "M2S_SP_REG_TN_I":0,
            "M2S_SP_REG_KP_U":0,
            "M2S_SP_REG_TN_U":0,
            "M2S_SP_REG_KP_M":0,
            "M2S_SP_REG_TN_M":0,
            "M2S_SP_REG_U_Ramp":0,
            "M2S_SP_REG_I_Ramp":0,
            "M2S_SP_REG_ParSet":0,
            "M2S_SP_REG_Mode":0,
            "M2S_SP_BATT_Model":0,
            "M2S_RS_CW2":0,
            "M2S_SP_P":0,
            "M2S_SP_BATT_C2":0,
            "M2S_SP_BATT_L1":0,
            "M2S_SP_BATT_U0_B":0,
            "M2S_SP_RPL_LF_Mode":0,
            "M2S_SP_RPL_MF_Mode":0,
            "M2S_SP_RPL_LF_Hz":0,
            "M2S_SP_RPL_LF_U":0,
            "M2S_SP_RPL_MF_Hz":0,
            "M2S_SP_RPL_MF_I":0,
            "M2S_SP_RPL_MF_U":0,
            "M2S_SP_SOC_C_Nom":0,
            "M2S_SP_SOC_0":0,
            "M2S_RS_SOC_0":0 }


    def __init__(self):
        pass


